### ISSUE TITLE
Need Help not working

### ISSUE THREAD

**Issue by ScripterSaurav** [ST1LLWATER/Anime_Watchlist_And_Tracker#1]
It's really good work . What is the password which askingin safe mode. But can you make a web app for anime streaming with js using api. Like this https://github.com/routayush1/animexninja
[Demo preview](https://animex.ninja/recentlyadded/1) .
Please bro or you can fix above repo to host on heroku .

**Comment by ST1LLWATER** [comment]
Bro first thing there is no api which gives u anime streaming service. Second for password its "stillwinter" and why do you want me to host it on heroku im yet on apply login feature on it and that concludes this project of mine.
