### ISSUE TITLE
The Logout Button

### ISSUE THREAD

**Issue by 0vol** [ST1LLWATER/Anime_Watchlist_And_Tracker#2]
The log out button can be enhanced if a confirmation dialog box appears after clicking on it.
![images](https://user-images.githubusercontent.com/91766105/176799748-3ddfe15d-1261-4272-a2a3-267d790f4e08.jpeg)

**Comment by 0vol** [comment]
looks like noone's there...

**Comment by ST1LLWATER** [comment]
Actually i would be remaking the app on different stack with custom backend. Ill implement it too.

**Comment by 0vol** [comment]
> Actually i would be remaking the app on different stack with custom backend. Ill implement it too.

ooh sorry i was'nt knowing that... by the way dis is noice...
